### ISSUE TITLE
./.firebase.json

### ISSUE THREAD

**Issue by zombodotcom** [Blemming/poe.house#1]
https://github.com/Blemming/poe.house/blob/37a5a688de16025addce6b223ca1270fa2e64b66/nuxt.config.js#L2

I am getting an issue when trying to build it to check out your cool way of showing hideouts. 

The issue is with the .firebase.json, am i supposed to make my own file with my certs in it?

Also that hideout.json file with the cdn stuff is awesome!

**Comment by Blemming** [comment]
firebase.json is your auth information, do not include it in your project or people will hack your firebase

the hideout.json file is just the data pulled from poedb, you can find more info [here](https://www.reddit.com/r/pathofexiledev/comments/a5fqjw/hideouts_api_by_poedb/)

GL
